name: pickit
description: A new Flutter project.
version: 0.0.1+7

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  audioplayers: ^0.20.1
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  dots_indicator: ^2.1.0
  equatable: ^2.0.3
  firebase_auth: ^3.3.4
  get: ^4.1.4
  firebase_core: ^1.24.0
  flutter_screenutil: ^5.0.1
  shared_preferences: ^2.0.13
  flutter_svg: ^0.23.0+1
#  image_picker: 0.8.6
  font_awesome_flutter: ^9.2.0
  camera: ^0.10.0
  google_sign_in: ^5.2.2
  firebase_core_platform_interface: 4.5.1
  firebase_messaging: ^13.0.4
  hive_flutter: ^1.1.0
  wakelock: ^0.6.1+2
  http: ^0.13.4
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  flutter_riverpod: ^1.0.3
  fluttertoast: ^8.0.9
  permission_handler: ^8.3.0
  flutter_fft: ^1.0.2+6
  flutter_sound: ^9.1.7
  firebase_crashlytics: ^2.9.0
  flutter_spinkit: ^5.1.0
#  razorpay_flutter: ^1.2.9
  table_calendar: ^3.0.3
  sqflite:
  video_player: ^2.2.10
  persistent_bottom_nav_bar: ^4.0.2
  webview_flutter: ^3.0.0
  cupertino_icons: ^1.0.2
  date_time_picker: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/videos/
    - assets/audio/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100

        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200

        - asset: fonts/Poppins-Light.ttf
          weight: 300

        - asset: fonts/Poppins-Regular.ttf
          weight: 400

        - asset: fonts/Poppins-Medium.ttf
          weight: 500

        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600

        - asset: fonts/Poppins-Bold.ttf
          weight: 700

        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800

        - asset: fonts/Poppins-Black.ttf
          weight: 900
